name: Build Workflow

on:
  push:
    branches:
      - master  # Trigger on push to the 'master' branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python 3.x
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install required packages
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build python3-pip

      # Install Conan
      - name: Install Conan
        run: |
          pip install conan

      # Ensure .profile is sourced
      - name: Source .profile
        run: |
          source ~/.profile

      # Run your build script and tests
      - name: Run build script and tests
        run: |
          cd Source
          python3 run.py build_all

      # Check the status of tests
      - name: Check test results
        run: |
          if [ $? -eq 0 ]; then
            echo "Tests passed successfully."
          else
            echo "Tests failed."
            exit 1  # If tests failed, exit with status 1 to fail the workflow
